app = "timegraph"
primary_region = "cdg"

[env]
  ENV = "production"
  PORT = "8080"
  TZ = "Europe/Paris"
  PUBLIC_URL = "timegraph.fly.dev"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 1
  processes = ["app"]
